version:  '3' 
services: 
 db: 
    container_name: mysql
    image: mysql:5.7
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 0430 
      MYSQL_DATABASE: oss
      MYSQL_USER: root
      MYSQL_PASSWORD: 0430 
    ports:
     - 6033:3306
    command: 
     - --character-set-server=utf8mb4 
     - --collation-server=utf8mb4_unicode_ci
 web: 
      build:
         context: ./php
         dockerfile: ./Dockerfile
      container_name: web
      depends_on: 
       - db
      ports: 
       - 8000:80
      volumes:
       - ./php:/var/www/html/



